version: '3.9'
services:
  # skynet:
  #   build:
  #     context: ./service/skynet
  #   image: skynet:1.7
  #   container_name: skynet1.7
  shiyanlou:
    image: skynet:1.7
    container_name: shiyanlou
    ports:
      - 8090:8090
    volumes:
      - ./server:/www/shiyanlou
    command: /skynet/skynet /www/shiyanlou/etc/config.cfg
